name: dev-centric-terraform

trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
    - fix/*
    - feat/*
  paths:
     include:
     - 'terraform/dev'
     
pool: azure-conatiner-app

stages:
  - stage: plan
    displayName: "Plan and Generate Artifact"
    variables:
      - group: ARM-dev
    jobs:
      - job: plan 
        displayName: Plan
        steps:
          - task: DownloadSecureFile@1
            name: sslCert
            displayName: 'Download SSL certificate'
            inputs:
              secureFile: 'azure.centric-dev.hanz.health.nz.pfx'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Agent.TempDirectory)'
              Contents: azure.centric-dev.hanz.health.nz.pfx
              TargetFolder: '$(System.DefaultWorkingDirectory)/terraform/dev'
          - script: | 
              git config --global url.https://$(System.AccessToken)@dev.azure.com.insteadOf "https://dev.azure.com"
            displayName: 'Set git config'
          - task: TerraformInstaller@0
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: '$(terraform_version)'
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              workingDirectory: 'terraform/dev'
              command: init
              backendServiceArm: 'ado-nr-centric-dev'
              backendAzureRmResourceGroupName: '$(ARM.ResourceGroup.dev.Name)'
              backendAzureRmStorageAccountName: '$(ARM.StorageAccount.dev.Name)'
              backendAzureRmContainerName: '$(ARM.StorageAccount.dev.Container.Name)'
              backendAzureRmKey: 'devcentricsoltfsae1'
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              workingDirectory: 'terraform/dev'
              command: validate
              backendServiceArm: 'ado-nr-centric-dev'
              backendAzureRmResourceGroupName: '$(ARM.ResourceGroup.dev.Name)'
              backendAzureRmStorageAccountName: '$(ARM.StorageAccount.dev.Name)'
              backendAzureRmContainerName: '$(ARM.StorageAccount.dev.Container.Name)'
              backendAzureRmKey: 'devcentricsoltfsae1'
          - task: TerraformTaskV2@2
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out $(Build.BuildId).tfplan'
              workingDirectory: 'terraform/dev'
              environmentServiceNameAzureRM: 'ado-nr-centric-dev'
          - task: ArchiveFiles@2
            displayName: 'Archive Terraform Plan Files'
            inputs:
              rootFolderOrFile: 'terraform/dev'
              includeRootFolder: false
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tfplan.tgz'
              replaceExistingArchive: true     
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Terraform Plan Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: '$(Build.BuildId)-tfplan'
              artifactType: pipeline
          - script: |
              cd $(System.DefaultWorkingDirectory)/terraform/dev
              ls -l
              terraform show -json $(System.DefaultWorkingDirectory)/terraform/dev/$(Build.BuildId).tfplan > tf.json
            displayName: 'Terraform Show'
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Terraform Show Artifact'
            inputs:
              targetPath: 'terraform/dev/tf.json'
              artifactName: 'tfshow'
              artifactType: pipeline
          - script: | 
              git config --global --unset url.https://$(System.AccessToken)@dev.azure.com.insteadOf
            displayName: 'Unset git config'
  - stage: compliance
    dependsOn: plan
    displayName: 'Static Code Analysis Stage'
    jobs:
      - job: ScanningCodes
        displayName: 'Run Checkov'
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: 'Download JSON Artifact'
          inputs:
            source: current 
            artifactName: 'tfshow'
            downloadPath: $(System.DefaultWorkingDirectory)/terraform/dev
        - script: |
                  mkdir CheckovReport
                  checkov -f $(System.DefaultWorkingDirectory)/terraform/dev/tf.json --framework terraform_plan --check MEDIUM --skip-check CKV_AZURE_39,CKV_AZURE_13 --output junitxml > $(System.DefaultWorkingDirectory)/CheckovReport/Checkov-Report.xml
          displayName: 'Do Checkov Static Code Analysis'
        - task: PublishTestResults@2
          displayName: Publish Checkov Test Results
          condition: succeededOrFailed()
          inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/Checkov-Report.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)/CheckovReport'
              mergeTestResults: false
              testRunTitle: Checkov Scan
              failTaskOnFailedTests: false
              publishRunAttachments: true
  - stage: approval
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: 
      - plan
      - compliance
    displayName: Validation
    jobs:
    - job: waitForValidation
      displayName: Wait for external validation
      pool: server
      timeoutInMinutes: 4320 # job times out in 3 days
      steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            sharan.nagulapalli@healthalliance.co.nz
          instructions: 'Please validate the terraform plan and resume'
          onTimeout: 'resume'
  - stage: deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: 
      - plan
      - compliance
      - approval
    displayName: Deploy
    variables:
      - group: ARM-dev
    jobs:  
    - job: apply
      displayName: Deploy Terraform plan
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download JSON Artifact'
        inputs:
          source: current 
          artifactName: '$(Build.BuildId)-tfplan'
          downloadPath: $(System.DefaultWorkingDirectory)/Artifact
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'Artifact/*.tgz' 
          destinationFolder:  'terraform/dev'
          overwriteExistingFiles: true
      - task: TerraformInstaller@0
        displayName: 'Terraform Install'
        inputs:
          terraformVersion: '$(terraform_version)'
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          workingDirectory: 'terraform/dev'
          command: 'init' 
          backendServiceArm: 'ado-nr-centric-dev'
          backendAzureRmResourceGroupName: '$(ARM.ResourceGroup.dev.Name)'
          backendAzureRmStorageAccountName: '$(ARM.StorageAccount.dev.Name)'
          backendAzureRmContainerName: '$(ARM.StorageAccount.dev.Container.Name)'
          backendAzureRmKey: 'devcentricsoltfsae1'
      - task: TerraformTaskV2@2
        displayName: 'Terraform Apply'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: 'terraform/dev'
          environmentServiceNameAzureRM: 'ado-nr-centric-dev'
